apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg
  labels:
    app: postgresql
    type: db
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  storageClassName: hostpath
  hostPath:
    path: /home/sguzman/Code/data/kube/postgres
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg
  labels:
    app: postgresql
    type: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: hostpath
  volumeName: pv-pg
